### ISSUE TITLE
Add the plugin to community-plugins list

### ISSUE THREAD

**Issue by talentlessguy** [ym-project/esbuild-stylus-loader#2]
Hello, thanks for creating this plugin!

esbuild recently started making a list of available plugins, maybe you would like to propose it here (only author of the plugin can add it):

https://github.com/esbuild/community-plugins

**Comment by ym-project** [comment]
Hi! Thank you for the information I will add the plugin to the list soon.

But in fact esbuild plugin API is poorly developed.
- doesn't support css inline sourcemaps;
- if I want to create external files for sourcemaps or for another reasons, I will not be able to add such files to esbuild output files list (at the moment it's impossible).

For this reason I abandoned the development of this plugin for a while.

**Comment by ym-project** [comment]
Done!
https://github.com/esbuild/community-plugins/pull/5
